//---------------------------------------------------
// This function loads the parts of your skeleton 
// (navbar, footer, and other things) into html doc. 
//---------------------------------------------------
function loadSkeleton(){
    firebase.auth().onAuthStateChanged(function (user) {
        if (user) {                   
            //if the pointer to "user" object is not null, then someone is logged in
            // User is signed in.
            // Do something for the user here.
            // console.log($('#navbarPlaceholder').load('./text/nav_after_login.html'));
            console.log($('#footerPlaceholder').load('./text/footer.html'));
        } else {
            // No user is signed in.
            // console.log($('#navbarPlaceholder').load('./text/nav_before_login.html'));
            console.log($('#footerPlaceholder').load('./text/footer.html'));
        }
    });
}
loadSkeleton();  //invoke the function

function addMenuListener(item) {
    console.log(item);
    document.getElementById(item).addEventListener("click", ()=>{
        passValue(item);
    })
}

function passValue(item) {
    localStorage.setItem("location", item);
    console.log("clicked..." + item);
    window.location.href = "./search_info.html";
}

addMenuListener("SE06");
addMenuListener("SE02");
addMenuListener("SW02");

/* Load locations JSON API data (generated by Mockaroo) to Firestore */
// Developed by Jimmy

async function readJSONbin() {
    const response = await fetch(
        'https://my.api.mockaroo.com/recycling_bins.json?key=95977410'
    )
    const data = await response.text(); //get text file, string
    const bins = JSON.parse(data); //convert to JSON

    for (bin of bins) {     
        let name = bin.name;
        
        db.collection("bins").add({
            bin_id: bin["bin_id"],
            city: bin.city,
            province: bin.province,
            country: bin.country,
            lat: bin.lat,
            lng: bin.lng,
            material_type: bin["material_type"]
        });
    }
}

